// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENTBUFFER_DIOGENES_GENERAL_H_
#define FLATBUFFERS_GENERATED_CLIENTBUFFER_DIOGENES_GENERAL_H_

#include "flatbuffers/flatbuffers.h"

namespace diogenes {
namespace general {

struct CB;

struct CB FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_CID = 4,
    VT_RID = 6,
    VT_DID = 8,
    VT_T1 = 10,
    VT_T2 = 12
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t rid() const {
    return GetField<uint64_t>(VT_RID, 0);
  }
  uint64_t did() const {
    return GetField<uint64_t>(VT_DID, 0);
  }
  const flatbuffers::String *t1() const {
    return GetPointer<const flatbuffers::String *>(VT_T1);
  }
  const flatbuffers::String *t2() const {
    return GetPointer<const flatbuffers::String *>(VT_T2);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID) &&
           VerifyField<uint64_t>(verifier, VT_RID) &&
           VerifyField<uint64_t>(verifier, VT_DID) &&
           VerifyOffset(verifier, VT_T1) &&
           verifier.Verify(t1()) &&
           VerifyOffset(verifier, VT_T2) &&
           verifier.Verify(t2()) &&
           verifier.EndTable();
  }
};

struct CBBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(CB::VT_CID, cid, 0);
  }
  void add_rid(uint64_t rid) {
    fbb_.AddElement<uint64_t>(CB::VT_RID, rid, 0);
  }
  void add_did(uint64_t did) {
    fbb_.AddElement<uint64_t>(CB::VT_DID, did, 0);
  }
  void add_t1(flatbuffers::Offset<flatbuffers::String> t1) {
    fbb_.AddOffset(CB::VT_T1, t1);
  }
  void add_t2(flatbuffers::Offset<flatbuffers::String> t2) {
    fbb_.AddOffset(CB::VT_T2, t2);
  }
  explicit CBBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  CBBuilder &operator=(const CBBuilder &);
  flatbuffers::Offset<CB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CB>(end);
    return o;
  }
};

inline flatbuffers::Offset<CB> CreateCB(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t rid = 0,
    uint64_t did = 0,
    flatbuffers::Offset<flatbuffers::String> t1 = 0,
    flatbuffers::Offset<flatbuffers::String> t2 = 0) {
  CBBuilder builder_(_fbb);
  builder_.add_did(did);
  builder_.add_rid(rid);
  builder_.add_cid(cid);
  builder_.add_t2(t2);
  builder_.add_t1(t1);
  return builder_.Finish();
}

inline flatbuffers::Offset<CB> CreateCBDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t rid = 0,
    uint64_t did = 0,
    const char *t1 = nullptr,
    const char *t2 = nullptr) {
  return diogenes::general::CreateCB(
      _fbb,
      cid,
      rid,
      did,
      t1 ? _fbb.CreateString(t1) : 0,
      t2 ? _fbb.CreateString(t2) : 0);
}

inline const diogenes::general::CB *GetCB(const void *buf) {
  return flatbuffers::GetRoot<diogenes::general::CB>(buf);
}

inline bool VerifyCBBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<diogenes::general::CB>(nullptr);
}

inline void FinishCBBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<diogenes::general::CB> root) {
  fbb.Finish(root);
}

}  // namespace general
}  // namespace diogenes

#endif  // FLATBUFFERS_GENERATED_CLIENTBUFFER_DIOGENES_GENERAL_H_
